name: Build CI

on:
  push:
    branches:
      - master
      - master-qa
  pull_request:
    branches:
      - master-qa

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: NDK install
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.1.7171670"
    - name: npm install
      run: npm ci
    - name: npm run android:assembleDebug
      run: |
        npm run build:prepare
        npm run android:assembleDebug

  build-ios:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm run pod:install
      run: npm run pod:install
    - name: xcodebuild
      run: |
        npm run build:prepare
        cd ios && xcodebuild -workspace eMobility.xcworkspace -scheme eMobility -configuration Debug CODE_SIGNING_ALLOWED=NO

